doc-warnings: yes
strictness: veryhigh
test-warnings: no
uses:
  - django
  - celery
max-line-length: 90
requirements:
  - python/requirements.txt
ignore-paths:
  - python/setup.py
  - python/scripts
  - python/tests
pylint:
  options:
    # Good variable names which should always be accepted, separated by a comma
    good-names: _,df,e,f,i,j,k,s,t,v,x,y
    # Regular expression matching correct variable names
    variable-rgx: "[a-z_][a-z0-9_]{1,30}$"
    # Maximum number of arguments for function / method
    max-args: 8
    # Maximum number of locals for function / method body
    max-locals: 20
    # Minimum number of public methods for a class (see R0903).
    min-public-methods: 1
pep8:
  disable:
    - N802